### ISSUE TITLE
Privacy preserving subject authentication mechanism for application with verifiable credentials

### ISSUE THREAD

**Issue by tplooker** [w3c/vc-di-bbs#37]
BBS+ Signatures are a generalized digital signature scheme appropriate for a variety of applications, however their most immediate application is in the context of [verifiable credentials](https://www.w3.org/TR/vc-data-model/).

[Verifiable credentials](https://www.w3.org/TR/vc-data-model/) in general define a cryptographically verifiable assertion format that allows an issuing authority to assert some information about a subject. In contrast to other assertion formats (e.g jwt based id_tokens in openid connect), verifiable credentials also focus on establishing a way for a credential subject to also authenticate, usually through a proof of key cryptographic mechanism.

The most common way this mechanism for subject authentication is realised in [verifiable credentials](https://www.w3.org/TR/vc-data-model/) is for the credential issued by the issuer to contain an identifier for the subject that when resolved contains the public cryptographic material required to verify a presentation of the credential originated from the subject it was bound to by the issuer.

```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/citizenship/v1",
    "https://w3c-ccg.github.io/ldp-bbs2020/context/v1"
  ],
  "type": ["VerifiableCredential", "PermanentResidentCard"],
  "issuer": "did:example:489398593",
  "identifier": "83627465",
  "name": "Permanent Resident Card",
  "description": "Government of Example Permanent Resident Card.",
  "issuanceDate": "2019-12-03T12:19:52Z",
  "expirationDate": "2029-12-03T12:19:52Z",
  "credentialSubject": {
    "id": "did:example:b34ca6cd37bbf23", // <= Unique identifier for the credential subject
    "type": ["PermanentResident", "Person"],
    "givenName": "JOHN",
    "familyName": "SMITH",
    "gender": "Male",
    "image": "data:image/png;base64,iVBORw0KGgokJggg==",
    "residentSince": "2015-01-01",
    "lprCategory": "C09",
    "lprNumber": "999-999-999",
    "commuterClassification": "C1",
    "birthCountry": "Bahamas",
    "birthDate": "1958-07-17"
  },
  "proof": {
    "type": "BbsBlsSignature2020",
    "created": "2020-04-26T04:21:07Z",
    "verificationMethod": "did:example:489398593#test",
    "proofPurpose": "assertionMethod",
    "proofValue": "jx2VhjyZqUT91e2OhzweJA7G2u2UvmiDtIfmr+wUWNHWno+UOAh0FaNpM8Br+5j2JBkH981/nO1I7/9PFaRrng6NXu7vzDroKtuyj6nHGkMmGq4OMmBzIqRnG3ybin/Sxmu5YwqOxPMRsWH3H+2wSA=="
  }
```

**Note** The current reference implementation of BBS+ signatures enables this mode today.

However, the problem with this model is that it enforces the presence of a unique identifier for the credential subject to always be present in the verifiable credential leading to the ability for relying parties / verifiers to be able to trivially track the subject across credential presentations.

Instead we need a subject authentication mechanism for [verifiable credentials](https://www.w3.org/TR/vc-data-model/) that does not require disclosing a unique identifier for the credential subject. But still relies on a proof of key cryptographic mechanism when the subject would like to authenticate the presentation of a verifiable credential.

In order to accomplish this we propose the following way.

**Simple Terms**

1. Issuer has a BLS 12-381 G2 public/private key pair they use to issue verifiable credentials
2. Subject has a BLS 12-381 G1 public/private key pair they will use to authenticate as the subject of a verifiable credential

When the issuer constructs a bound BBS+ signature one of the commitments they sign (other commitments being the individual statements in the verifiable credential), is the subjects BLS 12-381 G1 public key, therefore binding the signature to that key pair. In doing this in order for the subject to be able to derive a credential presentation for a credential featuring that signature they must possess the corresponding private key.

Examples

Issuer has a DID 
```
{
    "@context": "https://w3.org/ns/did/v1",
    "id": "did:example:12345",
    "assertionMethod": [
        {
            "id": "did:example:12345#1",
            "type": "Bls12381G2Key2020",
            "controller": "did:example:12345",
            "publicKeyBase58": "mrNfdUFeVwXmjQARQBhBFDCNLu2d4xbcRVVSrqShwgLi4pWWoEPog3JMGmzqS8PJ1WgAxkqD6x2FnSfkWBw2qikaKxyuZ1gUt3Z9BXbgBJAZ13jmFSGdGGGiGxGjNsRGuuJ"
        }
    ]
}
```

Subject has a DID 
```
{
    "@context": "https://w3.org/ns/did/v1",
    "id": "did:example:98765",
    "assertionMethod": [
        {
            "id": "did:example:98765#1",
            "type": "Bls12381G1Key2020",
            "controller": "did:example:98765",
            "publicKeyBase58": "mbsZx2rxTnboxrg1aE91Zc9iDDJcbeC1Q"
        }
    ]
}
```

Issuer issues credential of the following form
```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/citizenship/v1",
    "https://w3c-ccg.github.io/ldp-bbs2020/context/v1"
  ],
  "type": ["VerifiableCredential", "PermanentResidentCard"],
  "issuer": "did:example:12345",
  "identifier": "83627465",
  "name": "Permanent Resident Card",
  "description": "Government of Example Permanent Resident Card.",
  "issuanceDate": "2019-12-03T12:19:52Z",
  "expirationDate": "2029-12-03T12:19:52Z",
  "credentialSubject": {
    "type": ["PermanentResident", "Person"],
    "givenName": "JOHN",
    "familyName": "SMITH",
    "gender": "Male",
    "residentSince": "2015-01-01",
    "lprCategory": "C09",
    "lprNumber": "999-999-999",
    "commuterClassification": "C1",
    "birthCountry": "Bahamas",
    "birthDate": "1958-07-17"
  },
  "proof": {
    "type": "BbsBlsBoundSignature2020",
    "created": "2020-04-26T04:21:07Z",
    "verificationMethod": "did:example:12345#1",
    "subjectAuthenticationMethod": "did:example:98765#1", <= Note this is not a committed message in the signature it is merely here so that the subject knows which key the signature was bound to
    "proofPurpose": "assertionMethod",
    "proofValue": "jx2VhjyZqUT91e2OhzweJA7G2u2UvmiDtIfmr+wUWNHWno+UOAh0FaNpM8Br+5j2JBkH981/nO1I7/9PFaRrng6NXu7vzDroKtuyj6nHGkMmGq4OMmBzIqRnG3ybin/Sxmu5YwqOxPMRsWH3H+2wSA=="
  }
}
```

Subject can then create a selective proof (that requires them possessing the private key of the key pair the `BbsBlsBoundSignature2020` was bound to)

```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/citizenship/v1",
    "https://w3c-ccg.github.io/ldp-bbs2020/context/v1"
  ],
  "type": ["VerifiableCredential", "PermanentResidentCard"],
  "issuer": "did:example:12345",
  "identifier": "83627465",
  "name": "Permanent Resident Card",
  "description": "Government of Example Permanent Resident Card.",
  "issuanceDate": "2019-12-03T12:19:52Z",
  "expirationDate": "2029-12-03T12:19:52Z",
  "credentialSubject": {
    "type": ["PermanentResident", "Person"],
    "givenName": "JOHN",
    "familyName": "SMITH",
    "gender": "Male",
    "residentSince": "2015-01-01",
  },
  "proof": {
    "type": "BbsBlsBoundSignatureProof2020",
    "created": "2020-04-26T04:21:07Z",
    "verificationMethod": "did:example:12345#1",
    "proofPurpose": "assertionMethod",
    "proofValue": "jx2VhjyZqUT91e2OhzweJA7G2u2UvmiDtIfmr+wUWNHWno+UOAh0FaNpM8Br+5j2JBkH981/nO1I7/9PFaRrng6NXu7vzDroKtuyj6nHGkMmGq4OMmBzIqRnG3ybin/Sxmu5YwqOxPMRsWH3H+2wSA=="
  }
}
```

**Edit** 
- Updated the example to remove the image as per @OR13 comments below that were confusing the intent of the example
- Updated the subjectVerificationMethod field in the proof to be subjectAuthenticationMethod

**Comment by OR13** [comment]
`subjectVerficationMethod`.... is known to the issuer... why not use `credentialSubject.id` here... and simply not reveal that statement when constructing the selective disclosure presentation?... 

IIRC `credentialSubject.id` can be any URI... including `did:example:98765#1`

It feels like not revealing the credentialSubject.id but revealing image / age might be a better example.

Assuming `subject G1 Key` cannot be extracted from `bound signature proof proofValue` correct?

**Comment by tplooker** [comment]
> subjectVerficationMethod.... is known to the issuer... why not use credentialSubject.id here... and simply not reveal that statement when constructing the selective disclosure presentation?...

The main issue with this approach that then the generated N-Quads for the statements in the credentialSubject would then have to feature this ID meaning it would have to be known to a verifier and if not we would have to do some pretty weird credential specific logic about striping out credentialSubject.id before and after signature creation and verification.

> I assume this ZKP SD VC is then presented via something that supports replay attack mitigation?

Yeap much like the signature proofs to-date you are free to have other things feature in the proof e.g we support a nonce at the moment so if this is supplied by the verifier then you have replay attack prevention. For example a bound proof featuring a nonce would look like this 

```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/citizenship/v1",
    "https://w3c-ccg.github.io/ldp-bbs2020/context/v1"
  ],
  "type": ["PermanentResidentCard", "VerifiableCredential"],
  "description": "Government of Example Permanent Resident Card.",
  "identifier": "83627465",
  "name": "Permanent Resident Card",
  "credentialSubject": {
    "type": ["Person", "PermanentResident"],
    "familyName": "SMITH",
    "gender": "Male",
    "givenName": "JOHN"
  },
  "expirationDate": "2029-12-03T12:19:52Z",
  "issuanceDate": "2019-12-03T12:19:52Z",
  "issuer": "did:example:489398593",
  "proof": {
    "type": "BbsBlsBoundSignatureProof2020",
    "created": "2020-05-25T23:07:10Z",
    "verificationMethod": "did:example:489398593#test",
    "proofPurpose": "assertionMethod",
    "proofValue": "jx2VhjyZqUT91e2OhzweJA7G2u2UvmiDtIfmr+wUWNHWno+UOAh0FaNpM8Br+5j2JBkH981/nO1I7/9PFaRrng6NXu7vzDroKtuyj6nHGkMmGq4OMmBzIqRnG3ybin/Sxmu5YwqOxPMRsWH3H+2wSA=="
    "nonce": "37pdwue1a8FWLqgwCd0QJ0IJTFhp609KtxeCTWZGnfAVE+sOBDffYez+TY/bmVy+6z4="
  }
}
```

> its weird to think of putting a credential with no subject in a verifiable presentation.... it would feel more natural if BbsBlsBoundSignatureProof2020 was a VP and contained domain and challenge.

Yes so to be clear a VC of the form `BbsBlsBoundSignatureProof2020` would then be put into a VP like this where the inner proof authenticates the subject rather than needing _another_ proof

```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "type": "VerifiablePresentation",
  "verifiableCredential": [{
    "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "https://w3id.org/citizenship/v1",
        "https://w3c-ccg.github.io/ldp-bbs2020/context/v1"
    ],
    "type": ["PermanentResidentCard", "VerifiableCredential"],
    "description": "Government of Example Permanent Resident Card.",
    "identifier": "83627465",
    "name": "Permanent Resident Card",
    "credentialSubject": {
        "type": ["Person", "PermanentResident"],
        "familyName": "SMITH",
        "gender": "Male",
        "givenName": "JOHN"
    },
    "expirationDate": "2029-12-03T12:19:52Z",
    "issuanceDate": "2019-12-03T12:19:52Z",
    "issuer": "did:example:489398593",
    "proof": {
        "type": "BbsBlsBoundSignatureProof2020",
        "created": "2020-05-25T23:07:10Z",
        "verificationMethod": "did:example:489398593#test",
        "proofPurpose": "assertionMethod",
        "proofValue": "jx2VhjyZqUT91e2OhzweJA7G2u2UvmiDtIfmr+wUWNHWno+UOAh0FaNpM8Br+5j2JBkH981/nO1I7/9PFaRrng6NXu7vzDroKtuyj6nHGkMmGq4OMmBzIqRnG3ybin/Sxmu5YwqOxPMRsWH3H+2wSA=="
        "nonce": "37pdwue1a8FWLqgwCd0QJ0IJTFhp609KtxeCTWZGnfAVE+sOBDffYez+TY/bmVy+6z4="
    }
  }
  ]
}
```

**Comment by OR13** [comment]
This makes sense, I also agree its wise not to take the VC Data Model as a dendency... everything can fit in the `proof` object.

**Comment by OR13** [comment]
perhapse we would avoid the term subject....

`subjectAuthenticationMethod`

`authenticationMethod` / `boundAuthenticationMethod`...

**Comment by OR13** [comment]
https://github.com/multiformats/multicodec/pull/185 has been merged.

@tplooker wondering if we should define this key representation here now?

We should generate some test vectors for G1 / G2 and (G1 + G2), and then provide JWK, base58 and multicodec examples.

**Comment by dlongley** [comment]
My only comment is that you'll want to make sure that the proof purpose is for `authentication` when creating an authentication proof -- as opposed to `assertionMethod`.

**Comment by tplooker** [comment]
@dlongley I think this is worth pondering a little more. A `BbsBlsBoundSignatureProof2020 ` is unique in the sense that it is proving that the information was originally signed by the issuer and also authenticating the party who generated the proof. Currently in the example I have provided its quite clear about the role of the issuer but not the party who generated the proof.

**Comment by tplooker** [comment]
@OR13 agree it would be a good next step. As far as test vectors we have some preliminary support for JWK for G1 and G2 [here](https://github.com/mattrglobal/bls12381-key-pair/tree/master/__tests__/__fixtures__) although they would not rise to the standard of a test vector yet.

**Comment by kdenhartog** [comment]
@brentzundel I can't assign. Trying to tag you to see if that makes it possible.

**Comment by brentzundel** [comment]
commenting so I can be assigned

**Comment by OR13** [comment]
@brentzundel sorry I missed the session on this. I assigned you, lmk how I can help.

**Comment by brentzundel** [comment]
I am working on a PR to add this feature. It is not clear to me how the privacy of the holder is preserved when presenting a proof bound to their public BLS key. The example VP contains a reference to the holder's DID URL. 
@tplooker or @mikelodder7  can someone walk me through this step by step so I can write it up?

**Comment by mikelodder7** [comment]
@brentzundel thats why I wrote this up

https://github.com/mikelodder7/commit_twin.

The party storing the public keys knows your unique commitment in order to present but they don’t know your secret value. Also the public key is a pedersen commitment so it’s different per party and there’s no way it can be cross correlated between colluding parties

**Comment by tplooker** [comment]
@brentzundel thanks for reporting back, we should discuss this proposal further as the proposal of commit twin IMO is not directly about the credential binding technique instead it is how this binding can be used to achieve certain pseudonymity properties on top of the scheme. In essence I would like the binding to a credential to simply be a public key rather than a blinded public key (linked secret) because this makes the proof of private key signature more complex.

**Comment by tplooker** [comment]
@brentzundel understood, so if it is issuer correlation you are concerned about in this case, then it is solved by simply having a different public key per issuer. Because this public key is never revealed when generating a presentation with a verifier I believe all avenues of correlation we typically talk about are prevented?

**Comment by brentzundel** [comment]
okay, that makes sense. Thank you for clarifying that for me.
And thank you for walking me through this.

Here are the steps, as I understand them:
1. holder possesses a BLS public/private keypair
2. holder gives public key to issuer
3. issuer incorporates public key into issued credential
4. holder receives credential

5. verifier requests presentation
6. holder generates derived credential for presentation
7. holder generates proof of knowledge of private BLS key
8. verifier receives presentation
9. verifier verifies provided proofs

First, please let me know if I've missed something, or added something
unnecessary.
Next, the steps that are unclear to me still:
3. how does the issuer incorporate the holder's public key? Mathematically,
how does this work?
7. Is there even a step 7? Or is knowledge of the private key required in
order for the holder to perform step 6? Again, how does this work
mathematically?
9. I'm assuming that as soon as I understand 3 and 7, I will understand 9,
but detail here would also be appreciated.

**Comment by tplooker** [comment]
> First, please let me know if I've missed something, or added something unnecessary.

Yes that flow is correct.

> how does the issuer incorporate the holder's public key? Mathematically, how does this work?

As is the case with all "messages" signed to produce a BBS signature, if your issuer public key is in G2 then the messages being signed have to result in being commitments in G1. The subject's public key is really just a special case of one of these messages that is being signed, special because:
1. It uses the base generator in G1 (rather than an issuer specific generator)
2. Its a pre-commited message (the issuer doesn't know the value that went into creating the commitment i.e the secret key).

As to how the holder proves knowledge of the secret key to the issuer prior to issuance, because the public key is just an ordinary public key in G1 we can reach for more standard and well known signature schemes such as a BLS signature in either basic or proof of possession mode.

**Comment by tplooker** [comment]
That last point is why I felt the linked secret design added complexity that threatened implementability of the scheme as with a blinded public key or linked secret style binding, the proof of knowledge of the secret key becomes another thing you have to define, rather than saying "we'll just use BLS signatures for that piece".

**Comment by mikelodder7** [comment]
I agree with @brentzundel. I think that while this proposal is great, requires a good amount of cryptographic review and should not block the release of 2020 given the other changes we'd like to make to the spec after than.

**Comment by BasileiosKal** [comment]
Hi all!

I also have a question regarding this proposal.

### Question:

If I’m not mistaken, the BBS+ proofs of security against adaptive message attacks [here](https://eprint.iacr.org/2016/663.pdf) and [here](https://eprint.iacr.org/2008/136.pdf), take for granted that no message will be signed using the base generator of G1. If this is not enforced, a Holder could potentially forge a BBS+ signature.

For example, consider an (unblinded) BBS+ signature to the messages `m_1`, `m_2` of the form `(A, e, s)` where,

    A = (g_0 + g_0*HOLDER_SK + h_0*s + h_1*m_1 + h_2*m_2) * (1/(e+ISSUER_SK))

Here, `g_0` is the base generator of G1 and `h_i` are Issuer specific elements. By calculating `A*2` one can see that `(A*2, 2*s, e)` is a valid BBS+ signature to the messages `2 * m_1`, `2 * m_2`, and a Holder’s secret key; `2*HOLDER_SK + 1`, thus achieving forgery.

### Proposed Possible Solution:

If the above proves to be a problem, I think that not using the base generator of G1 and committing a message using any other (possible reserved) generator would work. That way the Holder’s secret message (private BLS key) becomes exactly like any other message signed by the Issuer. As a result, all the security proofs will continue to apply. Then, I think that security of the procedure could be proven, since if an adversary tries to create a PoK without knowing the Holder’s committed secret, will essentially have to forge a BBS+ signature.

Please let me know If there is anything wrong with my understanding :)

**Comment by mikelodder7** [comment]
That's not entirely accurate. The math doesn't exactly check out as you describe.
First off, let's define what a forgery means. It means that Alice initially had signed `HOLDER_SK` but can now use another value by manipulating the signature to show that something else was signed. Let's assume Alice multiplies by 2 as you suggest and use g_0 and Alice gives the signature and values to another party to run verify.

```
e(2 * A, W + e * g_2) != e(g_0 + g_0 *HOLDER_SK + h_0*2s + h_1*m_1 + h_2*m_2, g_2)
```

In this case, verify fails because of the multiply by two. If Alice sends anything other than the actual values signed, this also fails. We can see that using g_0 does not allow forgery in this case.

Next, if we look at the proof generation, this also fails. Now let's change the verify function to receive all signed values except a proof of a signature instead.

Verification becomes

```
A' = 2 * A * r1
A_bar = -e * A' + r1 * (g_0 + g_0 *HOLDER_SK + h_0*2s + h_1*m_1 + h_2*m_2)

e(A', w) != e(A_bar, g_2)
```

It still fails in this case. They are not equal. This equation holds even if all the messages are retained and not revealed. If Alice modifies any value including HOLDER_SK, the equation does not balance. 

Basically, using g_0 for the HOLDER_SK commitment doesn't necessarily harm it, but is not a good practice either. If Alice modifies the signature in any way or messages then the signature no longer verifies thus immune to adaptive message attacks.

My recommendation is if there is a desire to use the same generator point for HOLDER_SK across the ecosystem we pick a nothing up my sleeve value and use hash to curve to generate it. This results in a generator whose discrete log is unknown and thus cannot be used to manipulate in any way. But we can see that using the same generator here is not harmful.

**Comment by BasileiosKal** [comment]
>First off, let's define what a forgery means. It means that Alice initially had signed HOLDER_SK but can now use another value by manipulating the signature to show that something else was signed

@mikelodder7  Thank you very much for your reply. I entirely agree, but just to make sure that I correctly understood your definition;
   As a forgery, I denote the ability of an adversary to generate a valid signature for some values, on behalf of the Issuer, without knowing the Issuer’s secret key. Furthermore, a forgery can be achieved with an attack like an adaptive chosen-plaintext attack, which BBS+ signatures are proven to be secure against.

>    `e(2 * A, W + e * g_2) != e(g_0 + g_0 *HOLDER_SK + h_0*2s + h_1*m_1 + h_2*m_2, g_2)`

It is of-course correct that this equation does not hold, but that is because here Alice tries to verify the new (forged) signature `(A*2, 2s, e)` on the original messages `m_1` and `m_2` signed by the Issuer. The new signature, however, is a signature to the messages `2 x m_1` and `2 x m_2` (with ‘ x ’ I denote scalar multiplication), with the committed BLS secret key been `2 x HOLDER_SK + 1`. As a result -if I am not mistaken- the equation,

    e(A*2, W+e*g_2) = e(g_0 + g_0*(2 x HOLDER_SK + 1) + h_0*(2 x s) + h_1*(2 x m_1) + h_2*(2 x m_2), g_2)

would hold, meaning that `(A*2, 2s, e)` is a valid signature, created by Alice, on the messages `2 x m_1`, `2 x m_2` (which are different from the originally signed messages). Moreover, that signature is created without Alice knowing the Issuer’s secret key. So, if my definition above is correct, Alice does generate a forged BBS+ signature, by performing a chosen-plaintext attack (she has to first get a signature on the `m_1`, `m_2` from the issuer using her HOLDER_SK). In the end, even if the above is not considered a forgery, it does seem to me like a possible security problem.

**Comment by mikelodder7** [comment]
It’s not a security problem because that is similar to how the zero knowledge proof works. You randomize the signature and hidden values and balance the equation. So multiplying by 2 is similar to making a ZKP. The problem is if you modify the signature you have to modify EVERY value to make it work. Of course this has nothing to do with g_0. That’s a separate problem so there is no security problem here. It’s designed to work this way.

**Comment by BasileiosKal** [comment]
> It’s not a security problem because that is similar to how the zero knowledge proof works. You randomize the signature and hidden values and balance the equation. So multiplying by 2 is similar to making a ZKP.

I’m sorry, but I don’t think I understand your point. It is true that during ZKP generation `A` is multiplied by a random number, but I don’t see how that prevents Alice to forge a signature beforehand (assuming g_0 is used to commit messages). 

> Of course this has nothing to do with g_0  

Maybe I’m mistaken, but I think that the above method is only possible if a Holder can make commitments (like a BLS public key) using g_0. If that is not the case, simply multiplying `A` by something like 4 will create a `g_0*4` on the signature that will make the verification fail (of the original BBS+ signature, not the ZKP of knowledge). On the other hand, if we allow commitments to be made using g_0, the Holder could break `g_0*4` to `g_0 + g_0*3` and treat the first (g_0) as the standard part of the signature and the second (g_0*3) as part of a commitment. For that reason, I believe that it has to do with g_0.



Perhaps a better example will be the following. Suppose again that Alice executes a chosen message attack as before, and gets a BBS+ signature `(A, e, s)` from the Issuer on the messages `m_1`, `m_2` and her `Alice_SK`. 

The difference now is that instead of multiplying with 2 she will multiply by `k = m_3/m_1` where `m_3` is a new message that Alice wants to create a proof of knowledge for (but the Issuer hasn’t signed). The new signature now will be `(A*k, k*s, e)`, where, 

    A*k = g_0  +  g_0*(k x Allice_SK + k - 1) + h_0*(k x s) + h_1*m_3 + h_2*(k x m_2)

As before, that signature is a valid BBS+ signature to the messages `m_3`, `k x m_2`. Note however that the Issuer has not signed `m_3` (or `k x m_2`).

Since `(A*k, k*s, e)` is a valid BBS+ signature, Alice could also create a ZKP of knowledge using this signature, the messages `m_3`, `k x m_2` and  `k x Allice_SK + k - 1`. For example, if she calculates, 

    A' = k * A * r1
    A_bar = -e * A' + (g_0 + g_0 *(k x Allice_SK + k - 1) + h_0*(k x s) + h_1*m_3 + h_2*(k x m_2))*r1

Then the following equation (part of the ZKP of knowledge verification) holds,

    e(A', w) = e(A_bar, g_2)

In the end, Alice will manage to convince a Verifier that she possesses a valid signature on `m_3` (since she actually has it), while the Issuer has never signed this message. Wouldn’t that be considered a security problem (or a forgery)?

**Comment by mikelodder7** [comment]
Again look at your equations. They don’t balance. So no this is not a forgery

**Comment by mikelodder7** [comment]
Another reason is the messages must be revealed or use schnorr proofs. The verifier will only follow the verify equation which makes it so it doesnt balance

**Comment by BasileiosKal** [comment]
First, I want to really thank you for taking the time to answer me here!

> The problem with your math is your assuming you can divide in the exponent which you can’t really do in finite fields

All messages can be viewed (by Alice) as elements of Z*p, which means that she can divide them (multiply with the inverse technically). Then she could use the result of that division to the exponent. Alternatively, she could raise an element to the power of the inverse of the message she wants to divide with (the Verifier does not need to do those operations). Even if there was a way to ensure that the messages cannot be divided, Alice could just use her attack to gain a BBS+ signature to the message m_1 = 1, and as a result, no division is needed.  Lastly, in my first example I just raise to the power of 2, which should work regardless.

> Another reason is the messages must be revealed or use schnorr proofs. The verifier will only follow the verify equation which makes it so it doesnt balance

That is true, but Alice doesn’t have to reveal the original messages signed by the Issuer, but the ones she created the forged signature for. The entire point is for her to gain a BBS+ signature for some messages that the Issuer has not signed. For those messages (the ones that she will send to the Verifier), I don’t see why the equations don't balance. 

In the pdf [here](https://drive.google.com/file/d/18QsnJG6Lw2SSco2SCRY2JpBWs340jHTK/view?usp=sharing) I have a more detailed explanation of why I think those equations hold, using the notation from [here](https://eprint.iacr.org/2016/663.pdf) (which I think is more readable) and two simpler examples, similar to the ones I mentioned previously.

**Comment by BasileiosKal** [comment]
>  Multiplying by m3 means EVERY value is now m3 bigger

I don’t really see what the problem is if every value is m3 bigger, I would really appreciate it if you could explain that to me a little more. 

> If you multiply by 1/m3 it doesn't exactly carry straight thru as these the values are in-the-exponent which means it's not exactly divided. Instead, it would multiple 1/(e+x). 

Both (1/(e+x)) and 1/m3 are essentially elements of `Z*p` and they could be treated as any other `Z*p` element on the exponents. As a result, I think you could carry them through (since also the operation in any finite field is commutative).

**Comment by mikelodder7** [comment]
I think this would be better in a meeting than debating mathematics in GitHub. Email me and let’s discuss but your proposal for the vulnerability does not work

**Comment by BasileiosKal** [comment]
Hi all!

I met with @mikelodder7 where he was kind enough to explain to me what I was missing. 

In the end we concluded that using the base generator of G1 to create a commitment (BLS public key) may not be the best practice, since it can -in theory- lead to a potential forgery. 

Although this may not have any practical significance, perhaps it would be best to reserve a different generator (g0’) using a nothing-up-my-sleeve value as @mikelodder7 suggested, for the base generator of BLS keys. Doing that, BLS keys (using g0’) can still be used to authenticate the Holder, and the BBS+ signature will continue to be provably unforgeable.

**Comment by OR13** [comment]
I suggest we close this, and focus on cleaning up the spec.

**Comment by OR13** [comment]
Open, for a week, no objections to closing.... and a draft has begun to address, when the draft can be referenced, we will attempt to do so without creating a downref.

https://github.com/BasileiosKal/bbs-bound-signatures/blob/main/draft-bound-bbs-signatures.md
