### ISSUE TITLE
Complete FPWD

### ISSUE THREAD

**Issue by OR13** [w3c/vc-di-bbs#88]
@iherman I have merged #87 

The latest editors draft is in sync with the FPWD here: https://github.com/w3c/vc-di-bbs/tree/main/FPWD/2023-05-18

Please let me know if anything else is required.

**Comment by OR13** [comment]
ahh, sry... pub rules still needs addressing,  my mistake.

**Comment by OR13** [comment]
<img width="1557" alt="Screen Shot 2023-05-03 at 11 54 14 AM" src="https://user-images.githubusercontent.com/8295856/235986124-b01aaa23-9d48-4d09-9bb9-3819ad68d06e.png">
<img width="1808" alt="Screen Shot 2023-05-03 at 11 54 35 AM" src="https://user-images.githubusercontent.com/8295856/235986132-d9d976e9-cdb7-487a-ba5d-39cf3dca5f19.png">

should be good now.

**Comment by iherman** [comment]
I have downloaded the file, put it on /TR and I will start the official process. However, there are two link issues that _are_ bugs that you should chase down and handle before I initiate the preliminary check with the webmaster. See my screendump below that gives four errors. The second and the third are fine and are to be expected. The first and fourth seem to be a problem. The first one seems to be a wrong reference to the DI draft, the fourth seem to use non-existing fragment ID-s.

Ping me when you are done (please ping me explicitly with my id, so that I get a mail for action; alternatively, send me a mail). I will then initiate the preliminary publication request. 

Note that this does not hold back the official authorization of the FPWD only the publication itself.

![Screenshot 2023-05-04 at 09 01 22](https://user-images.githubusercontent.com/520723/236134071-4c07675b-abbb-418d-a527-1aa1c0756226.png)

**Comment by iherman** [comment]
See https://github.com/w3c/transitions/issues/503

**Comment by OR13** [comment]
Should be fixed in https://github.com/w3c/vc-di-bbs/commit/cb5c88d54c3da144299e2ea3f51a0dc513fda23d

**Comment by iherman** [comment]
Thanks @OR13. The document seems o.k. to me, I have sent an official publication request (the approval from the Director came in yesterday). Unless some unexpected happens it is now fully in the hands of the W3C Webmaster and comm team.
